name: lg_foodon_flutter
description: "lg_foodon_flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  #sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1 # 최신 버전
  avatar_glow: ^2.0.2 # 최신 버전 확인 후 업데이트


  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_slidable: ^3.1.1
  google_fonts: ^4.0.4

  flutter_gradient_animation_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
   - images/image_home/
   - images/product_image/
   - images/
   - images/icons/
   - images/newzen/

  fonts:
    - family: LGText
      fonts:
        - asset: fonts/LGEITextTTF-Bold.ttf
          weight: 700
        - asset: fonts/LGEITextTTF-Light.ttf
          weight: 300
        - asset: fonts/LGEITextTTF-Regular.ttf
          weight: 400
        - asset: fonts/LGEITextTTF-SemiBold.ttf
          weight: 600

